### ISSUE TITLE
Missed required parameter in documentation

### ISSUE THREAD

**Issue by mikhailsidorov** [sergeysolovev/ymaps#1]
Hi. There is a missing zoom parameter in the documentation example.

**Comment by sergeysolovev** [comment]
@mikhailsidorov 

thanks for your feedback! Is this a required parameter?

**Comment by mikhailsidorov** [comment]
Yes. There is an error with out it.

**Comment by sergeysolovev** [comment]
@mikhailsidorov I wouldn’t expect any errors in this case as the API endpoint hasn’t changed and Yandex even claims backwards compatibility. Anyway, let’s keep this closed.
